import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import type pg from 'pg';

/**
 * Minimal migration runner with rollback.
 *
 * Layout (in `migrationsDir`):
 *   0000_init.sql        <- generated by drizzle-kit (up)
 *   0000_init.down.sql   <- written by hand (down), required
 *
 * Applied migrations are tracked in `_migrations` with a checksum so that editing an
 * already-applied file is detected. Line endings are normalized before hashing so a
 * Windows checkout with CRLF does not look like a modified migration.
 * A Postgres advisory lock prevents two processes from migrating at the same time.
 */

const LOCK_ID = 727_001; // arbitrary, constant for this app
const TABLE = '_migrations';

export interface Migration {
  name: string;
  up: string;
  down: string;
  checksum: string;
}

export interface MigrationStatus {
  name: string;
  applied: boolean;
  appliedAt: Date | null;
}

export function defaultMigrationsDir(): string {
  // src/ and dist/ are both one level below the package root.
  return path.resolve(import.meta.dirname, '..', 'migrations');
}

const normalize = (sql: string) => sql.replace(/\r\n/g, '\n');
const checksumOf = (sql: string) => createHash('sha256').update(normalize(sql)).digest('hex');

export function readMigrations(dir: string = defaultMigrationsDir()): Migration[] {
  const ups = readdirSync(dir)
    .filter((f) => f.endsWith('.sql') && !f.endsWith('.down.sql'))
    .sort();
  return ups.map((file) => {
    const name = file.slice(0, -'.sql'.length);
    const downFile = path.join(dir, `${name}.down.sql`);
    if (!existsSync(downFile)) {
      throw new Error(`Migration ${name} has no rollback file ${name}.down.sql`);
    }
    const up = readFileSync(path.join(dir, file), 'utf8');
    return { name, up, down: readFileSync(downFile, 'utf8'), checksum: checksumOf(up) };
  });
}

async function withLock<T>(client: pg.ClientBase, fn: () => Promise<T>): Promise<T> {
  await client.query('SELECT pg_advisory_lock($1)', [LOCK_ID]);
  try {
    await client.query(
      `CREATE TABLE IF NOT EXISTS ${TABLE} (
         name text PRIMARY KEY,
         checksum text NOT NULL,
         applied_at timestamptz NOT NULL DEFAULT now()
       )`,
    );
    return await fn();
  } finally {
    await client.query('SELECT pg_advisory_unlock($1)', [LOCK_ID]);
  }
}

async function appliedRows(client: pg.ClientBase) {
  const res = await client.query<{ name: string; checksum: string; applied_at: Date }>(
    `SELECT name, checksum, applied_at FROM ${TABLE} ORDER BY name`,
  );
  return res.rows;
}

async function inTransaction(client: pg.ClientBase, fn: () => Promise<void>) {
  await client.query('BEGIN');
  try {
    await fn();
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  }
}

/** Applies all pending migrations in order. Returns names applied. */
export async function migrateUp(client: pg.ClientBase, dir?: string): Promise<string[]> {
  const migrations = readMigrations(dir);
  return withLock(client, async () => {
    const applied = new Map((await appliedRows(client)).map((r) => [r.name, r]));
    for (const row of applied.values()) {
      const m = migrations.find((x) => x.name === row.name);
      if (!m)
        throw new Error(`Applied migration ${row.name} is missing from ${TABLE} source files`);
      if (m.checksum !== row.checksum) {
        throw new Error(
          `Migration ${row.name} was modified after being applied (checksum mismatch)`,
        );
      }
    }
    const done: string[] = [];
    for (const m of migrations) {
      if (applied.has(m.name)) continue;
      await inTransaction(client, async () => {
        await client.query(m.up);
        await client.query(`INSERT INTO ${TABLE} (name, checksum) VALUES ($1, $2)`, [
          m.name,
          m.checksum,
        ]);
      });
      done.push(m.name);
    }
    return done;
  });
}

/** Rolls back the last `steps` applied migrations (newest first). Returns names rolled back. */
export async function migrateDown(
  client: pg.ClientBase,
  steps = 1,
  dir?: string,
): Promise<string[]> {
  if (!Number.isInteger(steps) || steps < 1) throw new Error('steps must be a positive integer');
  const migrations = readMigrations(dir);
  return withLock(client, async () => {
    const applied = (await appliedRows(client)).reverse().slice(0, steps);
    const done: string[] = [];
    for (const row of applied) {
      const m = migrations.find((x) => x.name === row.name);
      if (!m) throw new Error(`Cannot roll back ${row.name}: source files not found`);
      await inTransaction(client, async () => {
        await client.query(m.down);
        await client.query(`DELETE FROM ${TABLE} WHERE name = $1`, [m.name]);
      });
      done.push(m.name);
    }
    return done;
  });
}

export async function migrationStatus(
  client: pg.ClientBase,
  dir?: string,
): Promise<MigrationStatus[]> {
  const migrations = readMigrations(dir);
  return withLock(client, async () => {
    const applied = new Map((await appliedRows(client)).map((r) => [r.name, r]));
    return migrations.map((m) => ({
      name: m.name,
      applied: applied.has(m.name),
      appliedAt: applied.get(m.name)?.applied_at ?? null,
    }));
  });
}
